[install]
linker = "hoisted" # Configure the default linker strategy. Default "hoisted".
optional = true # Whether to install optional dependencies. Default true.
dev = true # Whether to install development dependencies. Default true.
peer = true # Whether to install peer dependencies. Default true.
exact = true # Whether to set an exact version in package.json. Default false.
saveTextLockfile = true # Whether to save a text lockfile (bunfig.lock.toml). Default true.
frozenLockfile = false # When true, bun install will not update bun.lock. Default false.
linkWorkspacePackages = true
# Only install package versions published at least 3 days ago
minimumReleaseAge = 259200
minimumReleaseAgeExcludes = ["@tsconfig/bun", "@types/bun", "@typescript/native-preview"]

[run]
bun = true # equivalent to `bun --bun` for all `bun run` commands
