packages: null

catalogs:
  lint:
    '@biomejs/biome': 2.2.4
  types:
    '@total-typescript/ts-reset': 0.6.1
    '@types/node': 24.1.0
  typescript:
    '@tsconfig/node-ts': 23.6.1
    '@tsconfig/node24': 24.0.1
    '@tsconfig/strictest': 2.0.5
    typescript: 5.9.2

enableGlobalVirtualStore: true
